In [1]:
from dotenv import load_dotenv
from os import getenv
from utils import CensusDataLoader
import pandas as pd

load_dotenv()

/home/thotsky/BrainVault/Projects/RHIP/utils/acs_loader.py:4: UserWarning: Mapping functions unavailable due to import error: ModuleNotFoundError. To use mapping features, ensure all dependencies are properly installed: pip install pytidycensus[map]
  import pytidycensus as tc

True

In [2]:
census_loader = CensusDataLoader(api_key=getenv("CENSUS_API_KEY"))

Census API key has been set for this session.

In [3]:
MOBILITY_VARS = {
    "MOVED_SAME_COUNTY_POVERTY": "B07012_010E",
    "MOVED_DIFF_COUNTY_POVERTY": "B07012_014E",
    "MOVED_DIFF_STATE_POVERTY": "B07012_018E",
    "MOVED_ABROAD_POVERTY": "B07012_022E",
    "MOVED_SAME_COUNTY_TOTAL": "B07012_009E",
    "MOVED_DIFF_COUNTY_TOTAL": "B07012_013E",
    "MOVED_DIFF_STATE_TOTAL": "B07012_017E",
    "MOVED_ABROAD_TOTAL": "B07012_021E",
}
SNAP_VARS = {
    "SNAP_TOTAL": "B22003_001E",  # Total households
    "RECEIVING": "B22003_002E",  # Received Food Stamps/SNAP in the past 12 months
}
EMPLOYMENT_VARS = {
    "LABOR_FORCE": "B23025_002E",  # In labor force
    "UNEMPLOYED": "B23025_005E",  # Civilian labor force: Unemployed
}

EDUCATION_VARS = {
    "EDUCATION_TOTAL": "B15003_001E",
    "GRADES": [f"B15003_{num:03d}E" for num in range(2, 17)],
}

QUALITY_VARS = {
    "TOTAL_PLUMBING": "B25047_001E",
    "LACK_PLUMBING": "B25047_003E",
    "TOTAL_KITCHEN": "B25051_001E",
    "LACK_KITCHEN": "B25051_003E",
}

POVERTY_VARS = {
    "POVERTY_TOTAL": "B17001_001E",
    "POVERTY": "B17001_002E",
}

# Separated this one since it overwrote TOTAL and looks like mortgage cost burden
MORTGAGE_VARS = {
    "MORTGAGE_TOTAL": "B25091_001E",
    "MORT_30_35": "B25091_008E",
    "MORT_35_40": "B25091_009E",
    "MORT_40_50": "B25091_010E",
    "MORT_50_PLUS": "B25091_011E",
    "NO_MORT_30_35": "B25091_019E",
    "NO_MORT_35_40": "B25091_020E",
    "NO_MORT_40_50": "B25091_021E",
    "NO_MORT_50_PLUS": "B25091_022E",
}

RENT_VARS = {
    "RENT_TOTAL": "B25070_001E",
    "RENT_30_35": "B25070_007E",
    "RENT_35_40": "B25070_008E",
    "RENT_40_50": "B25070_009E",
    "RENT_50_PLUS": "B25070_010E",
}

In [4]:
# Combine all variables into a single dictionary
vars_dict = {}

for d in [
    MOBILITY_VARS,
    SNAP_VARS,
    EMPLOYMENT_VARS,
    EDUCATION_VARS,
    QUALITY_VARS,
    POVERTY_VARS,
    MORTGAGE_VARS,
    RENT_VARS,
]:
    for key, val in d.items():
        if isinstance(val, list):
            for i, item in enumerate(val):
                vars_dict[f"{key}_{i+1}"] = item
        else:
            vars_dict[key] = val

In [5]:
if "acs_data" not in locals():
    acs_data = census_loader.fetch_multiple(variables=vars_dict, std_out=False) 

acs_data.head()

,GEOID,MOBILITY_TOTAL,SAME_HOUSE,MOVED_SAME_COUNTY,MOVED_DIFF_COUNTY,MOVED_DIFF_STATE,MOVED_ABROAD,SNAP_TOTAL,RECEIVING,LABOR_FORCE,...,MORT_50_PLUS_moe,NO_MORT_30_35_moe,NO_MORT_35_40_moe,NO_MORT_40_50_moe,NO_MORT_50_PLUS_moe,RENT_TOTAL_moe,RENT_30_35_moe,RENT_35_40_moe,RENT_40_50_moe,RENT_50_PLUS_moe
0,11001000101,22,22,0,0,0,0,851,0,801,...,8.0,15.0,15.0,80.0,11.0,103.0,37.0,13.0,33.0,30.0
1,11001000102,149,134,2,0,13,0,1845,75,1852,...,20.0,12.0,15.0,12.0,134.0,238.0,53.0,15.0,211.0,18.0
2,11001000201,61,61,0,0,0,0,0,0,1193,...,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0
3,11001000202,443,161,82,0,163,37,1823,0,2475,...,81.0,15.0,11.0,15.0,18.0,131.0,42.0,31.0,100.0,102.0
4,11001000300,281,160,51,0,70,0,2510,35,3528,...,35.0,13.0,16.0,21.0,35.0,233.0,128.0,82.0,49.0,73.0

In [9]:
MOBILITY_VARS

mobility_vars = acs_data[list(MOBILITY_VARS.keys())]
mobility_vars

,MOBILITY_TOTAL,SAME_HOUSE,MOVED_SAME_COUNTY,MOVED_DIFF_COUNTY,MOVED_DIFF_STATE,MOVED_ABROAD
0,22,22,0,0,0,0
1,149,134,2,0,13,0
2,61,61,0,0,0,0
3,443,161,82,0,163,37
4,281,160,51,0,70,0
...,...,...,...,...,...,...
6891,1127,1003,70,54,0,0
6892,511,511,0,0,0,0
6893,297,205,68,0,24,0
6894,364,355,0,9,0,0
6895,1989,1989,0,0,0,0